# Generated by Django 5.2.1 on 2026-06-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
