from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_page, name='dashboard'),
    path('upload/', views.upload_document, name='upload_document'),
    path('ai-convert/', views.ai_convert, name='ai_convert'),
    path('settings/', views.settings_page, name='settings'),
    path('profile/', views.profile_page, name='profile'),
    path('editor/', views.editor_page, name='editor'),
    path('editor/<str:project_id>/', views.editor_page, name='editor_with_id'),
    path('editor/<str:project_id>/save/', views.save_project, name='save_project'),
    path('editor/<str:project_id>/compile/', views.compile_project, name='compile_project'),
    path('templates/', views.templates_page, name='templates'),
    path('pricing/', views.pricing_page, name='pricing'),
    path('documentation/', views.documentation_page, name='documentation'),
    path('upgrade/', views.upgrade_to_pro_view, name='upgrade'),
    path('api-keys/create/', views.create_api_key_view, name='create_api_key'),
    path('api-keys/<str:key_id>/revoke/', views.revoke_api_key_view, name='revoke_api_key'),
    path('notifications/<str:notification_id>/read/', views.mark_notification_read_view, name='mark_notification_read'),
    path('preferences/save/', views.save_preferences_view, name='save_preferences'),
    path('preferences/get/', views.get_preferences_view, name='get_preferences'),
    path('editor/<str:project_id>/versions/', views.get_versions_view, name='get_versions'),
    path('editor/<str:project_id>/versions/create/', views.create_version_view, name='create_version'),
    path('editor/<str:project_id>/versions/<int:version_number>/restore/', views.restore_version_view, name='restore_version'),
    path('editor/<str:project_id>/share/', views.get_share_invitations_view, name='get_share_invitations'),
    path('editor/<str:project_id>/share/create/', views.create_share_invitation_view, name='create_share_invitation'),
    path('editor/<str:project_id>/share/<str:invitation_id>/revoke/', views.revoke_share_invitation_view, name='revoke_share_invitation'),
    path('editor/<str:project_id>/collaborators/<str:user_id>/remove/', views.remove_collaborator_view, name='remove_collaborator'),
    path('editor/<str:project_id>/reprocess/', views.reprocess_with_ai_view, name='reprocess_with_ai'),
    path('convert/<str:project_id>/', views.conversion_page, name='conversion_page'),
    path('convert/<str:project_id>/status/', views.conversion_status_json, name='conversion_status_json'),
]
